#!/bin/sh
# postinst script for SNAP

if [ "$1" = configure ]; then

    echo "Copying snap-neuro udev rules and restarting udev service..."
    cd /usr/local/bin
    mv snap-neuro/*.rules /etc/udev/rules.d
    service udev restart

    echo "Creating snap-neuro symlink to /usr/local/bin..."
    ln -sf snap-neuro/snap-neuro snap-neuro

    echo "Ensuring desktop entry permissions..."
    chmod 644 /usr/share/applications/snap-neuro.desktop

    echo "Updating desktop database..."
    update-desktop-database -q

    echo "Installation finished!"

fi

